steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -X \
          -Dsonar.projectKey=testingongcpci \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://34.135.193.41:9000 \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        apt-get update && apt-get install -y jq
        _STATUS=$(curl -s -X GET 'http://34.135.193.41:9000/api/qualitygates/project_status?projectKey=testingongcpci' -H 'Authorization:Basic $(echo -n "$$_SONAR_TOKEN:" | base64)' | jq -r .projectStatus.status)
        echo "Quality Gate Status:$_STATUS"
        if [ "$_STATUS" != "OK" ]; then
          echo "Raising a GitHub issue..."
          curl -X POST \
               -H "Authorization: token YOUR_GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -d '{"title":"Quality Gate Failed", "body":"Please check the SonarQube dashboard for details."}' \
               https://api.github.com/repos/shlokie1999/MoviePilot/issues
          else 1
        fi #
    id: 'fetch_quality_gate'
    secretEnv: ['_SONAR_TOKEN','_GITHUB_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/6
    env: '_SONAR_TOKEN'
  - versionName: projects/364895990307/secrets/mailgun-domain/versions/3
    env: '_GITHUB_TOKEN'
  
      
