steps:
  - name: 'python:3.8-slim'
    entrypoint: 'pip'
    args: ['install', 'truffleHog']

# Step to run TruffleHog
  - name: 'python:3.8-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        trufflehog --regex --repo_path . https://github.com/shlokie1999/MoviePilot --json src > trufflehog_output.json

# # Step to save the TruffleHog report to a GCS bucket
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['cp', 'trufflehog_output.json', 'gs://your-gcs-bucket/trufflehog_reports/']

#   - name: 'docker'
#     args: 
#       - 'pull'
#       - 'trufflesecurity/trufflehog:latest'
      
#   - name: 'docker'
#     args: 
#       - 'run'
#       - '--rm'
#       - '-v'
#       - './src:/src'
#       - 'trufflesecurity/trufflehog'
#       - 'github'
#       - '--repo'
#       - 'https://github.com/shlokie1999/MoviePilot'
#       - '--json'
#       # - ' > /src/trufflehog_output.json'

artifacts:
  objects:
    location: 'gs://trufflehog-scan/'  # Update this with your bucket name
    paths: ['trufflehog_output.json']


      
