steps:

  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.organization=workspace1101 \
          -Dsonar.projectKey=workspace1101_testinggcp \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      
        set -e
        apt-get update && apt-get install -y jq
        apt-get install -y curl
        response=(curl −sSfL −u $$_SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=workspace1101_testinggcp)
        status=(echo $response | jq -r ".projectStatus.status")
        echo $response
        echo $status
        echo "Quality gate status: $status"
        if [ "$status" != "OK" ]; then
          echo "Quality gate failed"
          exit 1
        fi
        #
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/2
    env: '_SONAR_TOKEN'  

 
  
