# options:
#   volumes:
#     - name: 'docker-socket'
#       path: '/var/run/docker.sock'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarqube:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--name', 'sonarqube_instance', '-d', '-p', '9000:9000', 'sonarqube:latest']
    id: start_sonar
    
  - name: 'gcr.io/cloud-builders/curl'
    args: ['http://localhost:9000']
    id: access_sonar
    
  - name: 'ubuntu'
    args: ['sleep', '120'] # waits for 2 minutes
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']
    
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -X \
          -Dsonar.projectKey=testingongcp \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/5
    env: '_SONAR_TOKEN'
  # - versionName: projects/364895990307/secrets/mailgun-domain/versions/3
  #   env: '_GITHUB_TOKEN'
  
      
