steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull','trufflesecurity/trufflehog']
  
  - name: 'trufflesecurity/trufflehog'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        trufflehog --help
        trufflehog git https://github.com/shlokie1999/MoviePilot --regex --entropy --json > trufflehog_output.json
        
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -s trufflehog_output.json ]; then
          echo "Trufflehog found secrets. Sending alert to Slack..."
        else
          echo "Trufflehog found no secrets."
        fi
  
  # - name: 'trufflesecurity/trufflehog'
  #   args: 
  #     - 'git'
  #     - 'https://github.com/shlokie1999/MoviePilot'
  #     - '--regex'
  #     - '--entropy'
  #     - '--json'
  #     - './trufflehog_output.json'
 
 
      

      
artifacts:
  objects:
    location: 'gs://trufflehog-scan/'  # Update this with your bucket name
    paths: ['trufflehog_output.json']


      
