steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['volume', 'create','--name', 'sonarqube_data']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['volume', 'create','--name', 'sonarqube_logs']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['volume', 'create', '--name','sonarqube_extensions']

  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'run'
    - '--rm'
    - '-p'
    - '9000:9000'
    - '-v'
    - 'sonarqube_extensions:/opt/sonarqube/extensions'
    - 'sonarqube:community'

  
      
