steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull','trufflesecurity/trufflehog']
  
  - name: 'trufflesecurity/trufflehog'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        trufflehog --help
        trufflehog github shlokie1999/MoviePilot --regex --entropy --json > trufflehog_output.json
  
  # - name: 'trufflesecurity/trufflehog'
  #   args: 
  #     - 'git'
  #     - 'https://github.com/shlokie1999/MoviePilot'
  #     - '--regex'
  #     - '--entropy'
  #     - '--json'
  #     - './trufflehog_output.json'
 
 
      
  # - name: 'docker'
  #   args: 
  #     - 'run'
  #     - '--rm'
  #     - '-v'
  #     - './src:/src'
  #     - 'trufflesecurity/trufflehog'
  #     - 'github'
  #     - '--repo'
  #     - 'https://github.com/shlokie1999/MoviePilot'
  #     - '--json'
  #     - '/src/trufflehog_output.json'
      
artifacts:
  objects:
    location: 'gs://trufflehog-scan/'  # Update this with your bucket name
    paths: ['trufflehog_output.json']


      
