steps:
  # Install phase
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "in the install phase"
        apt-get update && apt-get -y install jq
        apt-get install -y wget
        apt-get install -y maven
        
  # Pre-build phase: Instead of installing Nuclei via Go, pull and use the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'projectdiscovery/nuclei']

  # Clone nuclei-templates
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/projectdiscovery/nuclei-templates.git']

  # Nuclei help
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run','--rm','projectdiscovery/nuclei','-h']

  # Run nuclei scan using the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/app'
      - 'projectdiscovery/nuclei'
      - '-l'
      - '/app/target_urls.txt'
      - '-t'
      - '/app/nuclei-templates/'
      - '-o'
      - '/app/scan_report.json'
      - '-c'
      - '50'
      - '--timeout'
      - '10'
      - '--retries'
      - '3'
artifacts:
  objects:
    location: 'gs://nuclei-scan-reports/'  # Update this with your bucket name
    paths: ['scan_report.json']


      
