steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget tar golang 
        wget https://github.com/zricethezav/gitleaks/releases/download/v8.15.3/gitleaks_8.15.3_linux_x64.tar.gz
        mkdir gitleaks
        tar -xvzf gitleaks_8.15.3_linux_x64.tar.gz
        # sudo mv gitleaks_8.15.3_linux_x64 gitleaks
        chmod +x gitleaks
        mv gitleaks /usr/bin/
        gitleaks -h
        pwd
        gitleaks detect -s -r=/workspace/my_report.json
        ls
artifacts:
  objects:
    location: 'gs://gitleaks-scan-report/'  # Update this with your bucket name
    paths: ['my_report.json']


      
