steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -Dsonar.projectKey=testingongcp \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://35.238.39.251:9000 \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/3
    env: '_SONAR_TOKEN'  
  
      
