steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest']
    
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt -y upgrade
        apt-get update && apt-get install -y apparmor-utils apparmor-profiles apparmor-notify apparmor-profiles-extra docker-ce docker-ce-cli containerd.io
        /etc/init.d/apparmor start
        mount -tsecurityfs securityfs /sys/kernel/security
        cat /sys/kernel/security/apparmor/profiles
        # docker run --rm -i --security-opt apparmor=docker-default us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest
        ./test1.sh
        aa-status
        aa-enabled
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |    
        cp docker-deny /etc/apparmor.d/docker-deny
        apparmor_parser /etc/apparmor.d/docker-deny
        aa-enforce /etc/apparmor.d/docker-deny
        docker run --rm -i --security-opt apparmor=docker-deny us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest
        pwd
        ls   
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |    
        cp shfile /etc/apparmor.d/shfile
        apparmor_parser /etc/apparmor.d/shfile
        aa-enforce /etc/apparmor.d/shfile
        ./test1.sh
        pwd
        ls
        
