steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y apparmor-profiles
        apt-get install -y apparmor-utils
        aa-status
        echo "GRUB_CMDLINE_LINUX_DEFAULT=\"$(grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub | sed 's/"$/ apparmor=1 security=apparmor"/')\"" | tee /etc/default/grub
        grub-mkconfig -o /boot/grub/grub.cfg
        update-grub
        # apt -y upgrade 
        # apt-get install -y systemd
        # systemctl enable --now apparmor.service
        aa-enabled
        aa-status

        
