steps:
  - name: 'python:3.8-slim'
    entrypoint: /bin/sh
    args:
      - '-c'
      - 'pip install truffleHog'
      
  - name: 'trufflehog-scan'
    image: 'python:3.8-slim'  # Use a different name to indicate this is a new step
    entrypoint: /bin/sh
    args:
      - '-c'
      - 'trufflehog --regex --repo_path . https://github.com/shlokie1999/MoviePilot --json > trufflehog_scanReport.json'


#   - name: 'docker'
#     args: 
#       - 'pull'
#       - 'trufflesecurity/trufflehog:latest'
      
#   - name: 'docker'
#     args: 
#       - 'run'
#       - '--rm'
#       - '-v'
#       - './src:/src'
#       - 'trufflesecurity/trufflehog'
#       - 'github'
#       - '--repo'
#       - 'https://github.com/shlokie1999/MoviePilot'
#       - '--json'
#       # - ' > /src/trufflehog_output.json'

artifacts:
  objects:
    location: 'gs://trufflehog-scan/'  # Update this with your bucket name
    paths: ['trufflehog_scanReport.json']


      
