steps:
  # Install phase
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "in the install phase"
        apt-get update && apt-get -y install jq
        apt-get install -y wget
        apt-get install -y maven
        mkdir temp
        cd temp
        wget https://dl.google.com/go/go1.19.linux-amd64.tar.gz
        tar -xvf go1.19.linux-amd64.tar.gz
        mv go /usr/local
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        cd ..
        go version

  # Pre-build phase
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        nuclei -version
        nuclei -h
        git clone https://github.com/projectdiscovery/nuclei-templates.git
        ls

  # Build phase
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        nuclei -u http://localhost:8000 -t nuclei-templates/ -o scan_report.txt
        ls

artifacts:
  objects:
    location: 'gs://nuclei-scan-reports/'  # Update this with your bucket name
    paths: ['scan_report.txt']


      
