steps:
  
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run -d -p 9001:9000 sonarqube:latest
        sleep 120
        docker volume create sonarqube_data
        docker volume create sonarqube_extensions
        docker run -d \
            -p 9001:9000 \
            --name sonarqube \
            -v sonarqube_data:/opt/sonarqube/data \
            -v sonarqube_extensions:/opt/sonarqube/extensions \
              sonarqube:community 
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -X \
          -Dsonar.projectKey=testingongcp \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN']       
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/5
    env: '_SONAR_TOKEN'
  # - versionName: projects/364895990307/secrets/mailgun-domain/versions/3
  #   env: '_GITHUB_TOKEN'
  
      
