steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'us-central1-docker.pkg.dev/mcmp-integration-qa/apparmor/appimage:latest']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt -y upgrade
        apt-get update && apt-get install -y apparmor-utils apparmor-profiles apparmor-notify apparmor-profiles-extra systemd
        aa-enabled
        aa-status
        
        
