steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y pip npm curl
        pip install -r requirements.txt
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/ 
        snyk auth $$_API_TOKEN
        npm install snyk-to-html -g
        snyk test --file=requirements.txt --command=python3 --allow-missing --json-file-output=snyk_report.json
        snyk test --file=requirements.txt --command=python3 --allow-missing --severity-threshold=critical
        snyk-to-html -i snyk_report.json -o snyk_report.html
        snyk fix --file=requirements.txt
        snyk test --file=requirements.txt --command=python3 --allow-missing
    secretEnv: ['_API_TOKEN','_ORG_ID']
  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       apt-get update && apt-get install -y pip npm curl
  #       pip install -r requirements.txt
  #       curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
  #       chmod +x ./snyk
  #       mv ./snyk /usr/local/bin/ 
  #       snyk auth $$_API_TOKEN
  #       snyk code test --help
  #       npm install snyk-to-html -g
  #       snyk code test --org=$$_ORD_ID --json-file-output=snyk_report.json 
  #       cat snyk_report.json
  #       snyk-to-html -i snyk_report.json -o snyk_report.html
  #       snyk test --file=requirements.txt --command=python3 --allow-missing
  #       snyk code test --org=$$_ORD_ID --json-file-output=snyk_report.json --severity-threshold=high 
        
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/mailgun-domain/versions/6
    env: '_API_TOKEN'
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/8
    env: '_ORG_ID'
artifacts:
  objects:
    location: gs://snyk_scan
    paths: [snyk_report.html]       
