steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y pip curl
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/ 
        snyk auth $$_API_TOKEN
        snyk code test --help
        snyk code test --org=$$_ORD_ID --json-file-output=snyk_report.json
        cat snyk_report.json
    secretEnv: ['_API_TOKEN','_ORG_ID']
        
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/mailgun-domain/versions/6
    env: '_API_TOKEN'
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/8
    env: '_ORG_ID'
        
