steps:
  - name: 'ubuntu:latest'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git python3-pip
        pip3 install truffleHog
        pip3 show truffleHog
        trufflehog --regex --entropy=False --repo_path https://github.com/shlokie1999/MoviePilot --json > trufflehog_output.json

  # - name: 'docker'
  #   args: 
  #     - 'pull'
  #     - 'trufflesecurity/trufflehog:latest'
      
  # - name: 'docker'
  #   args: 
  #     - 'run'
  #     - '--rm'
  #     - '-v'
  #     - './src:/src'
  #     - 'trufflesecurity/trufflehog'
  #     - 'github'
  #     - '--repo'
  #     - 'https://github.com/shlokie1999/MoviePilot'
  #     - '--json'
  #     - '/src/trufflehog_output.json'
      
artifacts:
  objects:
    location: 'gs://trufflehog-scan/'  # Update this with your bucket name
    paths: ['trufflehog_output.json']


      
