steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']
  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -X \
          -Dsonar.projectKey=testingongcpci \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://34.135.193.41:9000 \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN']       
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/6
    env: '_SONAR_TOKEN'
  # - versionName: projects/364895990307/secrets/mailgun-domain/versions/3
  #   env: '_GITHUB_TOKEN'
  
      
