steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y apparmor-profiles
        apt-get install -y apparmor-utils
        aa-status

        
