steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'sonarsource/sonar-scanner-cli:latest']

  - name: 'sonarsource/sonar-scanner-cli:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sonar-scanner \
          -X \
          -Dsonar.projectKey=testingongcp \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://$$_IP_TOKEN:9000 \
          -Dsonar.login=$$_SONAR_TOKEN
    secretEnv: ['_SONAR_TOKEN','_IP_TOKEN']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y jq curl
        response=$(curl -X GET "https://$$_IP_TOKEN:9000/api/qualitygates/project_status?projectKey=testingongcp" -H "Authorization:$$_SONAR_TOKEN")
        status=$(echo "$response" | jq -r ".projectStatus.status")
        echo "Response: $response"
        echo "Quality gate status: $status"
        if [ "$status" != "OK" ]; then
          echo "Quality gate failed"
          curl -X POST \
               -H "Authorization: token $$_GITHUB_TOKEN " \
               -H "Accept: application/vnd.github.v3+json" \
               -d '{"title": "Quality gate failed in SonarQube", "body": "The quality gate check failed in Cloud Build for project: testingongcp. Please review the build logs and address the issues."}' \
               https://api.github.com/repos/shlokie1999/MoviePilot/issues
          exit 1
        fi
     secretEnv: ['_SONAR_TOKEN','_GITHUB_TOKEN','_IP_TOKEN_']
availableSecrets:
  secretManager:
  - versionName: projects/364895990307/secrets/sonarcloud-token/versions/4
    env: '_SONAR_TOKEN'
  - versionName: projects/364895990307/secrets/mailgun-domain/versions/4
    env: '_IP_TOKEN'
  - versionName: projects/364895990307/secrets/mailgun-domain/versions/3
    env: '_GITHUB_TOKEN'
  
      
