
steps:
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull','trufflesecurity/trufflehog']
  - name: 'trufflesecurity/trufflehog'
    args: ['git','https://github.com/shlokie1999/MoviePilot','--regex','--entropy','--only-verified','--json',' trufflehog_output.json']
  # - name: 'gcr.io/cloud-builders/docker'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       docker pull trufflesecurity/trufflehog:latest
  #       docker run --rm trufflesecurity/trufflehog git https://github.com/shlokie1999/MoviePilot --json > trufflehog_output.json

#   - name: 'python:3.8-slim'
#     entrypoint: /bin/sh
#     args:
#       - '-c'
#       - |
#         apt-get update && apt-get install -y git python3-pip
#         pip install --upgrade pip
#         pip install truffleHog
#         pip show truffleHog
#         trufflehog --regex --rules custom-secrets-config.json --entropy=False --repo_path . https://github.com/shlokie1999/MoviePilot --json > trufflehog_output.json

  # - name: 'docker'
  #   args: 
  #     - 'pull'
  #     - 'trufflesecurity/trufflehog:latest'
      
  # - name: 'trufflesecurity/trufflehog:latest'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       trufflehog --regex --rules custom-secrets-config.json --entropy=False https://github.com/shlokie1999/MoviePilot --json > trufflehog_output.json
      
  # - name: 'docker'
  #   args: 
  #     - 'run'
  #     - '--rm'
  #     - '-v'
  #     - './src:/src'
  #     - 'trufflesecurity/trufflehog'
  #     - 'github'
  #     - '--repo'
  #     - 'https://github.com/shlokie1999/MoviePilot'
  #     - '--json'
  #     - '/src/trufflehog_output.json'
      
artifacts:
  objects:
    location: 'gs://trufflehog-scan/'  # Update this with your bucket name
    paths: ['trufflehog_output.json']


      
